version: 0.1

phases:
  install:
    commands:
      - echo $SHELL
      - printenv
      - node --version
      - npm --version
  pre_build:
    commands:
      - npm i
  build:
    commands:
      - echo Build started on `date`
      - npm run test
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
    - '**/*'
