version: '2'

services:
  web:
    build: .
    volumes:
      - .:/app
    links:
      - db
    environment:
      - NODE_ENV=development
      - RDS_HOSTNAME=db
      - RDS_USERNAME=root
      - RDS_PASSWORD=root
    ports:
      - "3000:3000"
  db:
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - "3306:3306"

