version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8.11.3
      # https://circleci.com/docs/2.0/circleci-images/
    working_directory: ~/repo
    steps:
      - checkout
      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run: npm install

      - run: curl --fail $DOT_ENV_URL > .env

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      # run tests
      - run: npm test

      # run lint
      - run: npm run lint

